version: '3'

services:
  api01: &api
    image: prsgomes88/rinha-backend:latest

    hostname: api01
    container_name: api01
    ports:
      - "8081:8080"

    environment:

      DB_DRIVER: postgresql
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: rinhadb
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre

    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02

    ports:
      - "8082:8080"

    depends_on:
      - db

  db:
    container_name: rinha-backend-db
    image: postgres:latest

    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre

#    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgres.conf:/etc/postgresql/postgresql.conf

    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "210MB"

  nginx:
    image: nginx:latest
    container_name: nginx-rinha-2024

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api01
      - api02

    ports:
      - "9999:9999"

    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-2024